-- MySQL Script generated by MySQL Workbench
-- Wed May 13 15:41:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cediza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cediza` DEFAULT CHARACTER SET utf8 ;
USE `cediza` ;

-- -----------------------------------------------------
-- Table `cediza`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Usuarios` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `fechaNacimiento` DATE NULL,
  `DNI` VARCHAR(9) NULL,
  `Rol` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL DEFAULT 'paciente',
  `activo` BOOLEAN DEFAULT TRUE,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`nombreUsuario`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cediza`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Administrador`;
 
CREATE TABLE IF NOT EXISTS `cediza`.`Administrador` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_administrador_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 

-- -----------------------------------------------------
-- Table `cediza`.`Trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Trabajadores` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Trabajadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_trabajadores_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`coordinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`coordinadores` ;

CREATE TABLE IF NOT EXISTS `cediza`.`coordinadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `infoInteres` VARCHAR(200) NULL DEFAULT 'Nada añadido',
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_coordinadores_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Auxiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Auxiliares` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Auxiliares` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Horario` VARCHAR(50) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_auxiliares_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Especialistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Especialistas` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Especialistas` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Especialidad` VARCHAR(20) NOT NULL,
  `Horario` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_especialistas_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pacientes` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pacientes` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `diagnostico` VARCHAR(200) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pacientes_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pac_pri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pac_pri` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pac_pri` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `IVA` SMALLINT(21) NOT NULL DEFAULT 4,
  `cuenta` VARCHAR(100) NOT NULL,
  `horas` SMALLINT(10) NOT NULL DEFAULT 8,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pri_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pac_pub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pac_pub` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pac_pub` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Dias_ingresado` SMALLINT(31) NULL DEFAULT 0,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pub_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Enfermedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Enfermedades` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Enfermedades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`PacienteEnfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`PacienteEnfermedad` ;

CREATE TABLE IF NOT EXISTS `cediza`.`PacienteEnfermedad` (
  `paciente` VARCHAR(50) NOT NULL,
  `enfermedad_id` INT NOT NULL,
  PRIMARY KEY (`paciente`, `enfermedad_id`),
  INDEX `fk_paciente_enfermedad_enfermedad_idx` (`enfermedad_id` ASC),
  CONSTRAINT `fk_paciente_enfermedad_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_enfermedad_enfermedad`
    FOREIGN KEY (`enfermedad_id`)
    REFERENCES `cediza`.`Enfermedades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Familiares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Familiares` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Familiares` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Relacion` VARCHAR(45) NOT NULL DEFAULT 'Hij@',
  `Telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`Nombre`, `Paciente`),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_familiares_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Sesion` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Sesion` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `Paciente` VARCHAR(50) NOT NULL,
  `Especialista` VARCHAR(50) NOT NULL,
  `comentarios` VARCHAR(200) NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `Especialista_idx` (`Especialista` ASC),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_sesion_especialistas`
    FOREIGN KEY (`Especialista`)
    REFERENCES `cediza`.`Especialistas` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesion_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `cediza`.`comentarios` (
  `Auxiliar` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `nota` VARCHAR(200) NULL,
  PRIMARY KEY (`Auxiliar`, `Paciente`, `dia`),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_comentarios_trabajadores`
    FOREIGN KEY (`Auxiliar`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`EvaluacionProfesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`EvaluacionProfesional`;
 
CREATE TABLE IF NOT EXISTS `cediza`.`EvaluacionProfesional` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `Paciente` VARCHAR(50) NOT NULL,
  `Trabajador` VARCHAR(50) NOT NULL,
  `fecha` DATE NOT NULL,
  `movilidad` VARCHAR(45) NULL,
  `estadoEmocional` VARCHAR(45) NULL,
  `apetito` VARCHAR(45) NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `trabajador_idx` (`Trabajador` ASC),
  CONSTRAINT `fk_evaluacion_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_trabajadores`
    FOREIGN KEY (`Trabajador`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Informe`;
 
CREATE TABLE IF NOT EXISTS `cediza`.`Informe` (
  `referencia` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Trabajador` VARCHAR(50) NOT NULL,
  `fechaGeneracion` DATE NOT NULL,
  `periodoInicio` DATE NOT NULL,
  `periodoFin` DATE NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `trabajador_idx` (`Trabajador` ASC),
  CONSTRAINT `fk_informe_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_trabajadores`
    FOREIGN KEY (`Trabajador`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Factura`;
 
CREATE TABLE IF NOT EXISTS `cediza`.`Factura` (
  `codigoFactura` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Administrador` VARCHAR(50) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `importeTotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `estadoPago` VARCHAR(45) NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`codigoFactura`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `administrador_idx` (`Administrador` ASC),
  CONSTRAINT `fk_factura_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_administrador`
    FOREIGN KEY (`Administrador`)
    REFERENCES `cediza`.`Administrador` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Cuestionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Cuestionarios` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Cuestionarios` (
  `idCuestionario` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `fechaAsignacion` DATE NULL,
  PRIMARY KEY (`idCuestionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Preguntas` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `idCuestionario` INT NOT NULL,
  `enunciado` VARCHAR(300) NOT NULL,
  `tipoRespuesta` VARCHAR(45) NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `idCuestionario_idx` (`idCuestionario` ASC),
  CONSTRAINT `fk_preguntas_cuestionarios`
    FOREIGN KEY (`idCuestionario`)
    REFERENCES `cediza`.`Cuestionarios` (`idCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Respuestas` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `idPregunta` INT NOT NULL,
  `idPaciente` VARCHAR(50) NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `contenido` VARCHAR(500) NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `idPregunta_idx` (`idPregunta` ASC),
  INDEX `idPaciente_idx` (`idPaciente` ASC),
  CONSTRAINT `fk_respuestas_preguntas`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `cediza`.`Preguntas` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pacientes`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Datos iniciales
-- -----------------------------------------------------
INSERT INTO Enfermedades (nombre) VALUES
('Alzheimer'),
('Parkinson'),
('Demencia senil'),
('Artrosis'),
('Depresion')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;