-- MySQL Script generated by MySQL Workbench
-- Wed May 13 15:41:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cediza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cediza` DEFAULT CHARACTER SET utf8 ;
USE `cediza` ;

-- -----------------------------------------------------
-- Table `cediza`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Usuarios` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(9) NULL,
  `Rol` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT 'paciente',
  PRIMARY KEY (`nombreUsuario`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Trabajadores` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Trabajadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_trabajadores_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`coordinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`coordinadores` ;

CREATE TABLE IF NOT EXISTS `cediza`.`coordinadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `infoInteres` VARCHAR(200) NULL DEFAULT 'Nada añadido',
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_coordinadores_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Auxiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Auxiliares` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Auxiliares` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Horario` VARCHAR(50) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_auxiliares_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Especialistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Especialistas` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Especialistas` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Especialidad` VARCHAR(20) NOT NULL,
  `Horario` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_especialistas_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pacientes` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pacientes` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pacientes_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pac_pri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pac_pri` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pac_pri` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `IVA` SMALLINT(21) NOT NULL DEFAULT 4,
  `cuenta` VARCHAR(100) NOT NULL,
  `horas` SMALLINT(10) NOT NULL DEFAULT 8,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pri_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Familiares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Familiares` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Familiares` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Relación` VARCHAR(45) NOT NULL DEFAULT 'Hij@',
  `Telefono` INT(9) NULL,
  PRIMARY KEY (`Nombre`, `Paciente`),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_familiares_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Sesion` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Sesion` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `Paciente` VARCHAR(50) NOT NULL,
  `Especialista` VARCHAR(50) NOT NULL,
  `comentarios` VARCHAR(200) NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `Especialista_idx` (`Especialista` ASC),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_sesion_especialistas`
    FOREIGN KEY (`Especialista`)
    REFERENCES `cediza`.`Especialistas` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesion_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `cediza`.`comentarios` (
  `Auxiliar` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `nota` VARCHAR(200) NULL,
  PRIMARY KEY (`Auxiliar`, `Paciente`, `dia`),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_comentarios_trabajadores`
    FOREIGN KEY (`Auxiliar`)
    REFERENCES `cediza`.`Trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`Pac_pub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`Pac_pub` ;

CREATE TABLE IF NOT EXISTS `cediza`.`Pac_pub` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Dias_ingresado` SMALLINT(31) NULL DEFAULT 0,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pub_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`Pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;