-- MySQL Script generated by MySQL Workbench
-- Model: CEDIZA    Version: 3.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cediza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cediza` DEFAULT CHARACTER SET utf8;
USE `cediza`;

-- -----------------------------------------------------
-- Table `cediza`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`usuarios`;

CREATE TABLE IF NOT EXISTS `cediza`.`usuarios` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `fechaNacimiento` DATE NULL,
  `DNI` VARCHAR(9) NULL,
  `Rol` VARCHAR(45) NULL,
  `password` VARCHAR(60) NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`nombreUsuario`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`administrador`;

CREATE TABLE IF NOT EXISTS `cediza`.`administrador` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_administrador_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`trabajadores`;

CREATE TABLE IF NOT EXISTS `cediza`.`trabajadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_trabajadores_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`coordinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`coordinadores`;

CREATE TABLE IF NOT EXISTS `cediza`.`coordinadores` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `infoInteres` VARCHAR(200) NULL DEFAULT 'Nada añadido',
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_coordinadores_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`auxiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`auxiliares`;

CREATE TABLE IF NOT EXISTS `cediza`.`auxiliares` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Horario` VARCHAR(50) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_auxiliares_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`especialistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`especialistas`;

CREATE TABLE IF NOT EXISTS `cediza`.`especialistas` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Especialidad` VARCHAR(20) NOT NULL,
  `Horario` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_especialistas_trabajadores`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`pacientes`;

CREATE TABLE IF NOT EXISTS `cediza`.`pacientes` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `diagnostico` VARCHAR(200) NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pacientes_usuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`usuarios` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`pac_pri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`pac_pri`;

CREATE TABLE IF NOT EXISTS `cediza`.`pac_pri` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `IVA` SMALLINT NULL,
  `cuenta` VARCHAR(100) NULL,
  `horas` SMALLINT NULL,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pri_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`pac_pub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`pac_pub`;

CREATE TABLE IF NOT EXISTS `cediza`.`pac_pub` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `Dias_ingresado` SMALLINT NULL DEFAULT 0,
  PRIMARY KEY (`nombreUsuario`),
  CONSTRAINT `fk_pac_pub_pacientes`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`enfermedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`enfermedades`;

CREATE TABLE IF NOT EXISTS `cediza`.`enfermedades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`pacienteenfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`pacienteenfermedad`;

CREATE TABLE IF NOT EXISTS `cediza`.`pacienteenfermedad` (
  `paciente` VARCHAR(50) NOT NULL,
  `enfermedad_id` INT NOT NULL,
  PRIMARY KEY (`paciente`, `enfermedad_id`),
  CONSTRAINT `fk_pacienteenfermedad_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacienteenfermedad_enfermedades`
    FOREIGN KEY (`enfermedad_id`)
    REFERENCES `cediza`.`enfermedades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`familiares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`familiares`;

CREATE TABLE IF NOT EXISTS `cediza`.`familiares` (
  `idFamiliar` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Relacion` VARCHAR(45) NULL DEFAULT 'Hij@',
  `Telefono` INT(9) NULL,
  PRIMARY KEY (`idFamiliar`),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_familiares_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`factura`;

CREATE TABLE IF NOT EXISTS `cediza`.`factura` (
  `codigoFactura` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Administrador` VARCHAR(50) NOT NULL,
  `fechaEmision` DATE NULL,
  `importeTotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `estadoPago` VARCHAR(45) NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`codigoFactura`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `administrador_idx` (`Administrador` ASC),
  CONSTRAINT `fk_factura_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_administrador`
    FOREIGN KEY (`Administrador`)
    REFERENCES `cediza`.`administrador` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`sesion`;

CREATE TABLE IF NOT EXISTS `cediza`.`sesion` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `Paciente` VARCHAR(50) NOT NULL,
  `Especialista` VARCHAR(50) NOT NULL,
  `comentarios` VARCHAR(200) NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `especialista_idx` (`Especialista` ASC),
  INDEX `paciente_idx` (`Paciente` ASC),
  CONSTRAINT `fk_sesion_especialistas`
    FOREIGN KEY (`Especialista`)
    REFERENCES `cediza`.`especialistas` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesion_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`comentarios`;

CREATE TABLE IF NOT EXISTS `cediza`.`comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `Auxiliar` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `nota` VARCHAR(200) NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `auxiliar_idx` (`Auxiliar` ASC),
  CONSTRAINT `fk_comentarios_trabajadores`
    FOREIGN KEY (`Auxiliar`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cediza`.`evaluacionprofesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`evaluacionprofesional`;

CREATE TABLE IF NOT EXISTS `cediza`.`evaluacionprofesional` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `Paciente` VARCHAR(50) NOT NULL,
  `Trabajador` VARCHAR(50) NOT NULL,
  `fecha` DATE NOT NULL,
  `movilidad` VARCHAR(45) NULL,
  `estadoEmocional` VARCHAR(45) NULL,
  `apetito` VARCHAR(45) NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `trabajador_idx` (`Trabajador` ASC),
  CONSTRAINT `fk_evaluacion_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_trabajadores`
    FOREIGN KEY (`Trabajador`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`informe`;

CREATE TABLE IF NOT EXISTS `cediza`.`informe` (
  `referencia` VARCHAR(50) NOT NULL,
  `Paciente` VARCHAR(50) NOT NULL,
  `Trabajador` VARCHAR(50) NOT NULL,
  `fechaGeneracion` DATE NOT NULL,
  `periodoInicio` DATE NOT NULL,
  `periodoFin` DATE NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `paciente_idx` (`Paciente` ASC),
  INDEX `trabajador_idx` (`Trabajador` ASC),
  CONSTRAINT `fk_informe_pacientes`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_trabajadores`
    FOREIGN KEY (`Trabajador`)
    REFERENCES `cediza`.`trabajadores` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`cuestionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`cuestionarios`;

CREATE TABLE IF NOT EXISTS `cediza`.`cuestionarios` (
  `idCuestionario` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `fechaAsignacion` DATE NULL,
  PRIMARY KEY (`idCuestionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`preguntas`;

CREATE TABLE IF NOT EXISTS `cediza`.`preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `idCuestionario` INT NOT NULL,
  `enunciado` VARCHAR(300) NOT NULL,
  `tipoRespuesta` VARCHAR(45) NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `idCuestionario_idx` (`idCuestionario` ASC),
  CONSTRAINT `fk_preguntas_cuestionarios`
    FOREIGN KEY (`idCuestionario`)
    REFERENCES `cediza`.`cuestionarios` (`idCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cediza`.`respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cediza`.`respuestas`;

CREATE TABLE IF NOT EXISTS `cediza`.`respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `idPregunta` INT NOT NULL,
  `idPaciente` VARCHAR(50) NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `contenido` VARCHAR(500) NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `idPregunta_idx` (`idPregunta` ASC),
  INDEX `idPaciente_idx` (`idPaciente` ASC),
  CONSTRAINT `fk_respuestas_preguntas`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `cediza`.`preguntas` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pacientes`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `cediza`.`pacientes` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
